user:
  validate:
    name_max: 50
    email_max: 255
    pass_min: 6
  time_expired: 2
users_helper:
  size: 80
users_controller:
  page: 10
users:
   user:
     size_image: 50
paging:
  size: 10
answer:
  validate:
    content: 300
images:
  trainee:
    header:
      loder: /images/logo/loder.png
      logo: /images/logo/logo1.png
    home:
      git: /images/service/github-logo.jpg
  trainer:
    logo: /images/trainer/logo/loder.png
    logo1: /images/trainer/logo/logo.png
